### ISSUE TITLE
Unable to execute SQL queries with intersect/union/except keywords.

### ISSUE THREAD

**Issue by ymliucs** [SUDA-LA/SeSQL#1]
Thanks for releasing the high-quality Text2SQL dataset. However, when I use python's sqlite3 package to execute SQL queries with intersect/union/except keywords, I get the following error：
```
sqlite3.OperationalError: near "(": syntax error
```
DB: ```小说.db```  SQL: ```select 姓名 from 作者 order by 出生日期  union ( select 姓名 from 作者 order by 作品数量 asc limit 5 ) asc limit 3```  
My test code:
```python
import sqlite3
mydb = sqlite3.connect("小说.db")
mycursor = mydb.cursor()
mycursor.execute("select 姓名 from 作者 order by 出生日期  union ( select 姓名 from 作者 order by 作品数量 asc limit 5 ) asc limit 3")
columns_result = [col[0] for col in mycursor.description]
data = mycursor.fetchall()
mycursor.close()
mydb.close()
```

I test with a few versions of python and sqlite:
```
python 3.8.19 and sqlite 3.45.3
python 3.10.14 and pysqlite3 [0.4.6, 0.4.7, 0.4.8, 0.5.3]
```
It seems [all the constituent SELECTs must return the same number of result columns in a compound SELECT](https://stackoverflow.com/questions/56495461/using-a-union-function-after-a-join-getting-sqlite3-operationalerror-for-order). 
Any solution?

**Comment by 0Tzero** [comment]
它的sql语句本身就是错误的
